/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package panels;

import Frame.MainFrame;
import entity.main.Routine;
import javax.swing.JOptionPane;
import logic.Controller;
import panels.interfaces.PanelInterface;

/**
 *
 * @author Leon
 */
public class SelectPanel extends javax.swing.JPanel implements PanelInterface {

    /**
     * Creates new form SelectPanel
     */
    public SelectPanel() {
        initComponents();
        MainFrame mf = MainFrame.getFrame();
        mf.resetButtons();
        mf.setBackButtonEnabled(false);
        if (Controller.getInstance().getRoutine() == null) {
            mf.setNextButtonEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        loadRoutineButton = new javax.swing.JButton();
        newRoutineButton = new javax.swing.JButton();

        loadRoutineButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loadRoutineButton.setText("Load routine");
        loadRoutineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadRoutineButtonActionPerformed(evt);
            }
        });

        newRoutineButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        newRoutineButton.setText("Create new routine");
        newRoutineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRoutineButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadRoutineButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(newRoutineButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newRoutineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadRoutineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newRoutineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRoutineButtonActionPerformed
        if (Controller.getInstance().getRoutine() != null) {
            int result = JOptionPane.showConfirmDialog(
                    MainFrame.getFrame(), 
                    "<html><center>Are you sure you want to create a new routine?<br>All current progress will be lost.</center></html>", 
                    "Are you sure?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (result != 0) {
                return;
            }
        }
        Controller.getInstance().createNewRoutine();
        next();
    }//GEN-LAST:event_newRoutineButtonActionPerformed

    private void loadRoutineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadRoutineButtonActionPerformed
        boolean loaded = Controller.getInstance().loadRoutine();
        if (loaded) {
            MainFrame.getFrame().setPanel(new GeneralSettingsPanel());
        }
    }//GEN-LAST:event_loadRoutineButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton loadRoutineButton;
    private javax.swing.JButton newRoutineButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getTitle() {
        return "Select Routine";
    }

    @Override
    public String getHelp() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void next() {
        MainFrame.getFrame().setPanel(new GeneralSettingsPanel());
    }

    @Override
    public void back() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
