/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import entity.main.GeneralSettings;
import entity.main.Routine;
import java.awt.BorderLayout;
import java.awt.Desktop;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import logic.Controller;
import panels.GeneralSettingsPanel;
import panels.interfaces.PanelInterface;

/**
 *
 * @author Leon
 */
public class MainFrame extends javax.swing.JFrame {

    private JPanel mainPanel;
    
    private static MainFrame theFrame;
    
    /**
     * Creates new form StartScreen
     */
    public MainFrame() {
        initComponents();
        theFrame = this;
        setExtendedState(MAXIMIZED_BOTH);
        
        addWindowListener(
            new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    shutdown();
                }    
            }    
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        progressPanel = new javax.swing.JPanel();
        routinePanel = new javax.swing.JPanel();
        routineLabel = new javax.swing.JLabel();
        routineResultLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        madeByLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        slapGamingLink = new javax.swing.JLabel();
        authorPanel = new javax.swing.JPanel();
        authorLabel = new javax.swing.JLabel();
        authorResultLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        dropsPanel = new javax.swing.JPanel();
        dropsLabel = new javax.swing.JLabel();
        playerDropsLabel = new javax.swing.JLabel();
        mobDropsLabel = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        startInventoryPanel = new javax.swing.JPanel();
        startInventoryLabel = new javax.swing.JLabel();
        startInventoryResultLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        roundsPanel = new javax.swing.JPanel();
        roundsLabel = new javax.swing.JLabel();
        roundsResultLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        actionPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newRoutineItem = new javax.swing.JMenuItem();
        saveRoutineItem = new javax.swing.JMenuItem();
        loadRoutineItem = new javax.swing.JMenuItem();
        fileMenuSeperator = new javax.swing.JPopupMenu.Separator();
        exitItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        infoItem = new javax.swing.JMenuItem();
        pageHelpItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("StouxGames - SlapGaming");

        progressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        routineLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        routineLabel.setText("Current routine:");

        routineResultLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        routineResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        routineResultLabel.setText("No routine chosen yet.");

        javax.swing.GroupLayout routinePanelLayout = new javax.swing.GroupLayout(routinePanel);
        routinePanel.setLayout(routinePanelLayout);
        routinePanelLayout.setHorizontalGroup(
            routinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(routineLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(routineResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        routinePanelLayout.setVerticalGroup(
            routinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(routinePanelLayout.createSequentialGroup()
                .addComponent(routineLabel)
                .addGap(1, 1, 1)
                .addComponent(routineResultLabel))
        );

        madeByLabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        madeByLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        madeByLabel.setText("<html><center>Made by Stoux<br>StouxGames - Cake Defence</center></html>");

        slapGamingLink.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        slapGamingLink.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slapGamingLink.setText("<html><a href=\"www.slapgaming.com\">SlapGaming.com</a></html>");
        slapGamingLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        slapGamingLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                slapGamingLinkMouseClicked(evt);
            }
        });

        authorLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        authorLabel.setText("Author:");

        authorResultLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        authorResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        authorResultLabel.setText("No routine chosen yet.");

        javax.swing.GroupLayout authorPanelLayout = new javax.swing.GroupLayout(authorPanel);
        authorPanel.setLayout(authorPanelLayout);
        authorPanelLayout.setHorizontalGroup(
            authorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(authorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(authorResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        authorPanelLayout.setVerticalGroup(
            authorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authorPanelLayout.createSequentialGroup()
                .addComponent(authorLabel)
                .addGap(1, 1, 1)
                .addComponent(authorResultLabel))
        );

        dropsLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        dropsLabel.setText("Drops:");

        playerDropsLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        playerDropsLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        playerDropsLabel.setText("No routine chosen yet.");

        mobDropsLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        mobDropsLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mobDropsLabel.setText("No routine chosen yet.");

        javax.swing.GroupLayout dropsPanelLayout = new javax.swing.GroupLayout(dropsPanel);
        dropsPanel.setLayout(dropsPanelLayout);
        dropsPanelLayout.setHorizontalGroup(
            dropsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dropsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(playerDropsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
            .addComponent(mobDropsLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dropsPanelLayout.setVerticalGroup(
            dropsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dropsPanelLayout.createSequentialGroup()
                .addComponent(dropsLabel)
                .addGap(1, 1, 1)
                .addComponent(playerDropsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mobDropsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        startInventoryLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        startInventoryLabel.setText("Start inventory:");

        startInventoryResultLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        startInventoryResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        startInventoryResultLabel.setText("No routine chosen yet.");

        javax.swing.GroupLayout startInventoryPanelLayout = new javax.swing.GroupLayout(startInventoryPanel);
        startInventoryPanel.setLayout(startInventoryPanelLayout);
        startInventoryPanelLayout.setHorizontalGroup(
            startInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(startInventoryLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(startInventoryResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        startInventoryPanelLayout.setVerticalGroup(
            startInventoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startInventoryPanelLayout.createSequentialGroup()
                .addComponent(startInventoryLabel)
                .addGap(1, 1, 1)
                .addComponent(startInventoryResultLabel))
        );

        roundsLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        roundsLabel.setText("Number of rounds:");

        roundsResultLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        roundsResultLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        roundsResultLabel.setText("No routine chosen yet.");

        javax.swing.GroupLayout roundsPanelLayout = new javax.swing.GroupLayout(roundsPanel);
        roundsPanel.setLayout(roundsPanelLayout);
        roundsPanelLayout.setHorizontalGroup(
            roundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(roundsResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        roundsPanelLayout.setVerticalGroup(
            roundsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundsPanelLayout.createSequentialGroup()
                .addComponent(roundsLabel)
                .addGap(1, 1, 1)
                .addComponent(roundsResultLabel))
        );

        javax.swing.GroupLayout progressPanelLayout = new javax.swing.GroupLayout(progressPanel);
        progressPanel.setLayout(progressPanelLayout);
        progressPanelLayout.setHorizontalGroup(
            progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(progressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(routinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(slapGamingLink)
                    .addComponent(madeByLabel)
                    .addComponent(authorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addComponent(dropsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addComponent(startInventoryPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator5)
                    .addComponent(roundsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        progressPanelLayout.setVerticalGroup(
            progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(progressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(routinePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dropsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startInventoryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(roundsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(madeByLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slapGamingLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        buttonPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        nextButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
            .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        titleLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Title");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        actionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(actionPanel);

        fileMenu.setText("File");

        newRoutineItem.setText("New Routine");
        newRoutineItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newRoutineItemActionPerformed(evt);
            }
        });
        fileMenu.add(newRoutineItem);

        saveRoutineItem.setText("Save Routine");
        saveRoutineItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRoutineItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveRoutineItem);

        loadRoutineItem.setText("Load Routine");
        loadRoutineItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadRoutineItemActionPerformed(evt);
            }
        });
        fileMenu.add(loadRoutineItem);
        fileMenu.add(fileMenuSeperator);

        exitItem.setText("Exit");
        exitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitItem);

        jMenuBar1.add(fileMenu);

        helpMenu.setText("Help");

        infoItem.setText("Info");
        infoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoItemActionPerformed(evt);
            }
        });
        helpMenu.add(infoItem);

        pageHelpItem.setText("Page Help");
        pageHelpItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pageHelpItemActionPerformed(evt);
            }
        });
        helpMenu.add(pageHelpItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(progressPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slapGamingLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slapGamingLinkMouseClicked
        try {
            Desktop.getDesktop().browse(new URI("http://www.slapgaming.com"));
        } catch (URISyntaxException | IOException e) {
            throwError("Failed to open link :(");
        }
    }//GEN-LAST:event_slapGamingLinkMouseClicked

    private void saveRoutineItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRoutineItemActionPerformed
        Controller.getInstance().saveRoutine();
    }//GEN-LAST:event_saveRoutineItemActionPerformed

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (mainPanel instanceof PanelInterface) {
            ((PanelInterface) mainPanel).next();
        }
    }//GEN-LAST:event_nextButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        if (mainPanel instanceof PanelInterface) {
            ((PanelInterface) mainPanel).back();
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed
        shutdown();
    }//GEN-LAST:event_exitItemActionPerformed

    private void loadRoutineItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadRoutineItemActionPerformed
        boolean loaded = Controller.getInstance().loadRoutine();
        if (loaded) {
            setPanel(new GeneralSettingsPanel());
        }
    }//GEN-LAST:event_loadRoutineItemActionPerformed

    private void infoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoItemActionPerformed
        throwError("Sorry, not supported yet!");
    }//GEN-LAST:event_infoItemActionPerformed

    private void pageHelpItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pageHelpItemActionPerformed
        throwError("Sorry, not supported yet!");
    }//GEN-LAST:event_pageHelpItemActionPerformed

    private void newRoutineItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newRoutineItemActionPerformed
        if (Controller.getInstance().getRoutine() != null) {
            int result = JOptionPane.showConfirmDialog(
                    MainFrame.getFrame(), 
                    "<html><center>Are you sure you want to create a new routine?<br>All unsaved progress will be lost.</center></html>", 
                    "Are you sure?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (result != 0) {
                return;
            }
        }
        Controller.getInstance().createNewRoutine();
        setPanel(new GeneralSettingsPanel());
    }//GEN-LAST:event_newRoutineItemActionPerformed

    /**
     * Set the action panel to a new panel
     * @param panel The new panel
     */
    public void setPanel(JPanel panel) {
        updateSidebar();
        mainPanel = panel;
        actionPanel.removeAll();
        actionPanel.setLayout(new BorderLayout());
        actionPanel.add(panel);
        revalidate();
        repaint();
        try {
            if (panel instanceof PanelInterface) {
                PanelInterface pi = (PanelInterface) panel;
                titleLabel.setText(pi.getTitle());
            }
        } catch (UnsupportedOperationException e) {
            e.printStackTrace();
        }
    }
    
    public void resetButtons() {
        nextButton.setEnabled(true);
        backButton.setEnabled(true);
        nextButton.setText("Next");
        backButton.setText("Back");
    }
    
    public static void setPanel(JPanel thePanel, JPanel toPanel) {
        thePanel.removeAll();
        thePanel.setLayout(new BorderLayout());
        thePanel.add(toPanel);
        theFrame.revalidate();
        theFrame.repaint();
    }
    
    public static void throwError(String title) {
        JOptionPane.showMessageDialog(theFrame, title, "Error.", JOptionPane.ERROR_MESSAGE);
    }
    
    public static MainFrame getFrame() {
        return theFrame;
    }
    
    public void setBackButtonEnabled(boolean enabled) {
        backButton.setEnabled(enabled);
    }
    public void setBackButtonText(String text) {
        backButton.setText(text);
    }
    public void setNextButtonEnabled(boolean enabled) {
        nextButton.setEnabled(enabled);
    }
    public void setNextButtonText(String text) {
        nextButton.setText(text);
    }
    
    private void shutdown() {
        Routine r = Controller.getInstance().getRoutine();
        if (r != null) {
            GeneralSettings gs = r.getGeneralSettings();
            if (gs != null) {
                int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit? All progress will be lost.",
                        "Are you sure?", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (result != 0) {
                    return;
                }
            }
        }
        System.exit(0);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JPanel authorPanel;
    private javax.swing.JLabel authorResultLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel dropsLabel;
    private javax.swing.JPanel dropsPanel;
    private javax.swing.JMenuItem exitItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPopupMenu.Separator fileMenuSeperator;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem infoItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JMenuItem loadRoutineItem;
    private javax.swing.JLabel madeByLabel;
    private javax.swing.JLabel mobDropsLabel;
    private javax.swing.JMenuItem newRoutineItem;
    private javax.swing.JButton nextButton;
    private javax.swing.JMenuItem pageHelpItem;
    private javax.swing.JLabel playerDropsLabel;
    private javax.swing.JPanel progressPanel;
    private javax.swing.JLabel roundsLabel;
    private javax.swing.JPanel roundsPanel;
    private javax.swing.JLabel roundsResultLabel;
    private javax.swing.JLabel routineLabel;
    private javax.swing.JPanel routinePanel;
    private javax.swing.JLabel routineResultLabel;
    private javax.swing.JMenuItem saveRoutineItem;
    private javax.swing.JLabel slapGamingLink;
    private javax.swing.JLabel startInventoryLabel;
    private javax.swing.JPanel startInventoryPanel;
    private javax.swing.JLabel startInventoryResultLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    // End of variables declaration//GEN-END:variables

    public void updateSidebar() {
        Routine routine = Controller.getInstance().getRoutine();
        if (routine == null) {
            String n = "No routine chosen yet.";
            routineResultLabel.setText(n);
            authorResultLabel.setText(n);
            playerDropsLabel.setText(n);
            mobDropsLabel.setText(n);
            startInventoryResultLabel.setText(n);
            roundsResultLabel.setText(n);
            return;
        }
        GeneralSettings gs = routine.getGeneralSettings();
        if (gs != null) {
            routineResultLabel.setText(gs.getRoutinename());
            authorResultLabel.setText(gs.getAuthor());
            playerDropsLabel.setText("Player: " + toYesNo(gs.isPlayerDropOnDeath()));
            mobDropsLabel.setText("Mobs: " + toYesNo(gs.isMobDropOnDeath()));
        } else {
            setToUnknown(routineResultLabel);
            setToUnknown(authorResultLabel);
            setToUnknown(playerDropsLabel);
            setToUnknown(mobDropsLabel);
        }
        if (routine.getStartReward() == null) {
            startInventoryResultLabel.setText("Not set");
        } else {
            startInventoryResultLabel.setText("Set");
        }
        int rounds = routine.getRounds().size();
        roundsResultLabel.setText(rounds + " rounds");
    }
    
    private void setToUnknown(JLabel label) {
        label.setText("Unknown");
    }
    
    private String toYesNo(boolean yesNo) {
        if (yesNo) return "Yes";
        else return "No";
    }
    
    



}
