name: StouxGames
version: 0.1
description: Stoux Mini-Games plugin
# Lots and lots of credit to Naithantu
# Helping me out, teaching me stuff about bukkit
# Giving me an example of a good plugin setup
author: Stoux

# My website
website: www.stoux.nl/StouxGames


main: nl.stoux.stouxgames.StouxGames
database: false
depend: [WorldGuard, WorldEdit]
softdepend: [TabAPI, TagAPI, Essentials]

commands:
  gleave:
    description: Same as vipitem.
    usage: /vip
  warpsonic:
     description: Warps you to the sonic world to race.
  sonic:
    description: Main command for the sonic racetrack.